[workspace]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "flatbuffers"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test-flatbuffers = "mojo run test_flatbuffers.mojo"
bench-flatbuffers = "mojo run bench_flatbuffers.mojo"
format = "mblack flatbuffers.mojo test_flatbuffers.mojo"

[dependencies]
mojo = ">=0.26.2"
